<?php

use App\Models\Event;
use App\Models\EventResource;
use App\Models\Faq;
use App\Models\NewsPost;
use App\Models\Page;
use App\Models\Program;
use App\Models\Session;
use App\Models\Slide;

return [
    'types' => [
        'slides' => [
            'model' => Slide::class,
            'label' => 'Hero slides',
            'singular' => 'Hero slide',
            'description' => 'Manage the large stories and calls-to-action at the top of the homepage.',
            'title_field' => 'title',
            'order_by' => 'sort_order',
            'fields' => [
                ['name' => 'eyebrow', 'label' => 'Eyebrow', 'type' => 'text', 'translatable' => true],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'translatable' => true, 'required' => true],
                ['name' => 'subtitle', 'label' => 'Supporting text', 'type' => 'textarea', 'translatable' => true],
                ['name' => 'button_text', 'label' => 'Button label', 'type' => 'text', 'translatable' => true],
                ['name' => 'button_url', 'label' => 'Button URL', 'type' => 'link', 'help' => 'Use an HTTP(S) URL or a page path such as /events. Local page links follow the visitor language.'],
                ['name' => 'image', 'label' => 'Background image', 'type' => 'image'],
                ['name' => 'video_url', 'label' => 'Background video', 'type' => 'video', 'help' => 'An HTTPS video URL, or a managed video path beginning /videos/fsrp/. The background image is used while the video loads.'],
                ['name' => 'sort_order', 'label' => 'Display order', 'type' => 'number', 'default' => 0],
                ['name' => 'is_active', 'label' => 'Visible on website', 'type' => 'boolean', 'default' => true],
            ],
        ],
        'events' => [
            'model' => Event::class,
            'label' => 'Events',
            'singular' => 'Event',
            'description' => 'Publish upcoming, ongoing, and past convenings.',
            'title_field' => 'title',
            'order_by' => 'start_at',
            'order_direction' => 'desc',
            'fields' => [
                ['name' => 'title', 'label' => 'Event title', 'type' => 'text', 'translatable' => true, 'required' => true],
                ['name' => 'slug', 'label' => 'URL slug', 'type' => 'slug', 'required' => true],
                ['name' => 'excerpt', 'label' => 'Short description', 'type' => 'textarea', 'translatable' => true],
                ['name' => 'body', 'label' => 'Full description', 'type' => 'richtext', 'translatable' => true],
                ['name' => 'venue', 'label' => 'Venue / platform', 'type' => 'text', 'translatable' => true],
                ['name' => 'start_at', 'label' => 'Starts', 'type' => 'datetime'],
                ['name' => 'end_at', 'label' => 'Ends', 'type' => 'datetime'],
                ['name' => 'mode', 'label' => 'Delivery mode', 'type' => 'select', 'options' => ['in-person' => 'In person', 'online' => 'Online', 'hybrid' => 'Hybrid'], 'required' => true],
                ['name' => 'registration_url', 'label' => 'Registration URL', 'type' => 'url'],
                ['name' => 'image', 'label' => 'Event image', 'type' => 'image'],
                ['name' => 'is_featured', 'label' => 'Featured event', 'type' => 'boolean'],
                ['name' => 'is_published', 'label' => 'Published', 'type' => 'boolean', 'default' => true],
            ],
        ],
        'sessions' => [
            'model' => Session::class,
            'label' => 'Sessions',
            'singular' => 'Session',
            'description' => 'Build the programme agenda and connect sessions to events.',
            'title_field' => 'title',
            'order_by' => 'start_at',
            'fields' => [
                ['name' => 'event_id', 'label' => 'Event', 'type' => 'event'],
                ['name' => 'title', 'label' => 'Session title', 'type' => 'text', 'translatable' => true, 'required' => true],
                ['name' => 'summary', 'label' => 'Summary', 'type' => 'textarea', 'translatable' => true],
                ['name' => 'speaker_name', 'label' => 'Speaker name', 'type' => 'text', 'translatable' => true],
                ['name' => 'speaker_role', 'label' => 'Speaker role', 'type' => 'text', 'translatable' => true],
                ['name' => 'location', 'label' => 'Room / link label', 'type' => 'text', 'translatable' => true],
                ['name' => 'track', 'label' => 'Programme track', 'type' => 'text', 'translatable' => true],
                ['name' => 'is_all_day', 'label' => 'Day programme / timings to be confirmed', 'type' => 'boolean', 'description' => 'Display the session date without a specific start or end time.'],
                ['name' => 'start_at', 'label' => 'Starts', 'type' => 'datetime'],
                ['name' => 'end_at', 'label' => 'Ends', 'type' => 'datetime'],
                ['name' => 'format', 'label' => 'Format', 'type' => 'select', 'options' => ['keynote' => 'Keynote', 'plenary' => 'Plenary', 'panel' => 'Panel', 'workshop' => 'Workshop', 'roundtable' => 'Roundtable', 'fireside_chat' => 'Fireside chat', 'technical_lab' => 'Technical lab', 'showcase' => 'Showcase', 'networking' => 'Networking'], 'required' => true],
                ['name' => 'sort_order', 'label' => 'Display order', 'type' => 'number', 'default' => 0],
                ['name' => 'is_published', 'label' => 'Published', 'type' => 'boolean', 'default' => true],
            ],
        ],
        'resources' => [
            'model' => EventResource::class,
            'label' => 'Downloads & resources',
            'singular' => 'Event resource',
            'description' => 'Publish programme outlines, event briefs, presentations, and reports for participants to download.',
            'title_field' => 'title',
            'order_by' => 'sort_order',
            'fields' => [
                ['name' => 'event_id', 'label' => 'Related event', 'type' => 'event', 'help' => 'Resources linked to draft events stay hidden until the event is published.'],
                ['name' => 'title', 'label' => 'Document title', 'type' => 'text', 'translatable' => true, 'required' => true],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'translatable' => true],
                ['name' => 'category', 'label' => 'Resource category', 'type' => 'select', 'options' => EventResource::CATEGORIES, 'required' => true, 'default' => 'programme'],
                ['name' => 'language', 'label' => 'Document language', 'type' => 'select', 'options' => ['en' => 'English', 'fr' => 'French', 'ar' => 'Arabic', 'pt' => 'Portuguese', 'es' => 'Spanish', 'sw' => 'Swahili'], 'required' => true, 'default' => 'en'],
                ['name' => 'document', 'label' => 'Document file', 'type' => 'document', 'required' => true],
                ['name' => 'sort_order', 'label' => 'Display order', 'type' => 'number', 'default' => 0],
                ['name' => 'is_published', 'label' => 'Published', 'type' => 'boolean', 'default' => false],
            ],
        ],
        'news' => [
            'model' => NewsPost::class,
            'label' => 'News',
            'singular' => 'News story',
            'description' => 'Share announcements, outcomes, and programme updates.',
            'title_field' => 'title',
            'order_by' => 'published_at',
            'order_direction' => 'desc',
            'fields' => [
                ['name' => 'title', 'label' => 'Headline', 'type' => 'text', 'translatable' => true, 'required' => true],
                ['name' => 'slug', 'label' => 'URL slug', 'type' => 'slug', 'required' => true],
                ['name' => 'category', 'label' => 'Category', 'type' => 'text', 'translatable' => true],
                ['name' => 'excerpt', 'label' => 'Summary', 'type' => 'textarea', 'translatable' => true],
                ['name' => 'body', 'label' => 'Article', 'type' => 'richtext', 'translatable' => true],
                ['name' => 'image', 'label' => 'Featured image', 'type' => 'image'],
                ['name' => 'published_at', 'label' => 'Publication date', 'type' => 'datetime'],
                ['name' => 'is_featured', 'label' => 'Featured story', 'type' => 'boolean'],
                ['name' => 'is_published', 'label' => 'Published', 'type' => 'boolean', 'default' => true],
            ],
        ],
        'programs' => [
            'model' => Program::class,
            'label' => 'Programme outline',
            'singular' => 'Programme track',
            'description' => 'Structure the strategic themes and delivery areas of the programme.',
            'title_field' => 'title',
            'order_by' => 'sort_order',
            'fields' => [
                ['name' => 'title', 'label' => 'Track title', 'type' => 'text', 'translatable' => true, 'required' => true],
                ['name' => 'slug', 'label' => 'URL slug', 'type' => 'slug', 'required' => true],
                ['name' => 'excerpt', 'label' => 'Short description', 'type' => 'textarea', 'translatable' => true],
                ['name' => 'body', 'label' => 'Full outline', 'type' => 'richtext', 'translatable' => true],
                ['name' => 'icon', 'label' => 'Icon', 'type' => 'select', 'options' => ['compass' => 'Compass', 'spark' => 'Innovation spark', 'leaf' => 'Climate leaf', 'bridge' => 'Regional bridge']],
                ['name' => 'sort_order', 'label' => 'Display order', 'type' => 'number', 'default' => 0],
                ['name' => 'is_published', 'label' => 'Published', 'type' => 'boolean', 'default' => true],
            ],
        ],
        'faqs' => [
            'model' => Faq::class,
            'label' => 'Frequently asked questions',
            'singular' => 'FAQ',
            'description' => 'Answer common participant questions in every supported language.',
            'title_field' => 'question',
            'order_by' => 'sort_order',
            'fields' => [
                ['name' => 'category', 'label' => 'Category', 'type' => 'text', 'translatable' => true],
                ['name' => 'question', 'label' => 'Question', 'type' => 'text', 'translatable' => true, 'required' => true],
                ['name' => 'answer', 'label' => 'Answer', 'type' => 'textarea', 'translatable' => true, 'required' => true],
                ['name' => 'sort_order', 'label' => 'Display order', 'type' => 'number', 'default' => 0],
                ['name' => 'is_published', 'label' => 'Published', 'type' => 'boolean', 'default' => true],
            ],
        ],
        'pages' => [
            'model' => Page::class,
            'label' => 'Pages',
            'singular' => 'Page',
            'description' => 'Manage the main About page and future editorial pages.',
            'title_field' => 'title',
            'order_by' => 'key',
            'fields' => [
                ['name' => 'key', 'label' => 'Page key', 'type' => 'text', 'required' => true],
                ['name' => 'eyebrow', 'label' => 'Eyebrow', 'type' => 'text', 'translatable' => true],
                ['name' => 'title', 'label' => 'Page title', 'type' => 'text', 'translatable' => true, 'required' => true],
                ['name' => 'body', 'label' => 'Page content', 'type' => 'richtext', 'translatable' => true],
                ['name' => 'image', 'label' => 'Page image', 'type' => 'image'],
                ['name' => 'is_published', 'label' => 'Published', 'type' => 'boolean', 'default' => true],
            ],
        ],
    ],
];
